plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

group = "fr.rader"

repositories {
    maven {
        url "https://maven.shedaniel.me/"
    }

    maven {
        url "https://maven.terraformersmc.com/releases/"
        content {
            includeGroup "com.terraformersmc"
        }
    }
}

base {
    archivesName = "timeless-${project.minecraft_version}-${project.mod_version}"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation("com.terraformersmc:modmenu:${project.modmenu_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    implementation("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.3.6")))
}

loom.accessWidenerPath = rootProject.file("src/main/resources/timeless.accesswidener")

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

processResources {
    inputs.property("version", project.version)
    inputs.property("loader_version", project.loader_version)

    filteringCharset("UTF-8")
    filesMatching("fabric.mod.json") {
        expand(
                "version": project.version,
                "loader_version": project.loader_version
        )
    }
}
